### ISSUE TITLE
/v1/devices/

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/edge-node-manager#188]
@josephroberts you open to adding a `/v1/devices/` which the same as `/v1/devices/<deviceId>` but it returns all registered devices?

**Comment by josephroberts** [comment]
@craig-mulligan sure, when do you need it by?

**Comment by craig-mulligan** [comment]
It'd be nice to have it before next weeks check in, so like monday/tues?

**Comment by josephroberts** [comment]
yeah no worries. I will have it done first thing tuesday morning

**Comment by craig-mulligan** [comment]
Awesome! thanks dude 👍

**Comment by craig-mulligan** [comment]
Hey @josephroberts, turns out I don't actually need this, I'm just monitoring the edge-nodes via the api, either way I think it makes sense to have this endpoint, but there is no real push for it currently.
