### ISSUE TITLE
ENM is not creating AP on Pi 3 + ESP8266

### ISSUE THREAD

**Issue by numpad0** [resin-io/edge-node-manager#197]
Tried pushing ENM to Raspberry Pi 3, Resin OS 2.3.0+rev1(dev), ESP8266, but the Pi is not creating AP at all.

**Comment by josephroberts** [comment]
Have you created a dependent application and set the `RESIN_HOST_TYPE=esp8266` Fleet Configuration?

**Comment by numpad0** [comment]
I got it working! I was setting `RESIN_HOST_TYPE=esp8266` and `RESIN_SUPERVISOR_DELTA=1` to the *host* application, not on *dependent* side! Thanks!
